const fs = require('fs');
const path = require('path');

// Lire la variable d'environnement API_BASE (définie sur Vercel)
const apiBase = process.env.API_BASE || 'http://localhost:3000';

const dest = path.join(__dirname, 'config.js');
const content = `// generated by build\nwindow.API_BASE = '${apiBase.replace(/'/g, "\\'")}';\n`;

fs.writeFileSync(dest, content, 'utf8');
console.log(`Wrote ${dest} with API_BASE=${apiBase}`);
